name: Build Android App

on:
  push:
    branches: ["*", "*"]
  pull_request:
    branches: ["*", "*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle*') }}

      - run: chmod +x artnetMobile/gradlew 
      
      - run: ./gradlew build 
        working-directory: artnetMobile